name: flutter_myntra_clone
description: Myntra clone in Flutter

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1
  pin_code_fields: ^8.0.1
  cupertino_icons: ^1.0.0
  card_swiper: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/blank_image.png
